// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcjtgmzzhfkolsjzwcsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjanRnbXp6aGZrb2xzanp3Y3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTc1NDAsImV4cCI6MjA2ODE3MzU0MH0.qo2Er4HyxgC_mSzwOtOakaVEGBLuGgQeYCL59lvz6Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});